++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf

++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf

++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf

loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf

++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
v
v
v
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf
loremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjfloremdsjf

++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++++++++[>+++++++[-.]<-]++
++++++[>+++++++[-.]<-]++